# Generated by Django 5.1.6 on 2026-05-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classRank',
            field=models.CharField(default='Unranked', max_length=17),
        ),
    ]
