# Generated by Django 5.1.6 on 2026-06-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_classrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('xp_threshold', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-xp_threshold'],
            },
        ),
    ]
